[
  "./img/img-background/photo0.jpg",
  "./img/img-background/photo1.jpg",
  "./img/img-background/photo2.jpg",
  "./img/img-background/photo3.jpg",
  "./img/img-background/photo4.jpg",
  "./img/img-background/photo5.jpg",
  "./img/img-background/photo6.jpg",
  "./img/img-background/photo7.jpg",
];
